"""Validation helpers for Gemini-generated quiz payloads."""

from pydantic import BaseModel, Field, ValidationError, field_validator


class GeneratedQuestion(BaseModel):
    """One multiple-choice question generated by Gemini."""

    content: str = Field(min_length=5)
    type: str
    options: list[str] = Field(min_length=4, max_length=4)
    correct_answer: str = Field(min_length=1)
    explanation: str = Field(min_length=3)

    @field_validator("type")
    @classmethod
    def validate_type(cls, value: str) -> str:
        """Restrict generated questions to the supported MCQ type."""

        if value != "mcq":
            raise ValueError("Question type must be 'mcq'.")
        return value

    @field_validator("correct_answer")
    @classmethod
    def validate_correct_answer(cls, value: str, info) -> str:
        """Ensure the correct answer matches one of the provided options."""

        options = info.data.get("options", [])
        if value not in options:
            raise ValueError("correct_answer must match one of the options.")
        return value


class GeneratedQuiz(BaseModel):
    """Structured quiz payload returned by Gemini."""

    title: str = Field(min_length=3)
    questions: list[GeneratedQuestion] = Field(min_length=1)


def validate_generated_quiz(payload: dict) -> GeneratedQuiz:
    """Validate a Gemini JSON payload against the LearnQUIZ quiz schema."""

    try:
        return GeneratedQuiz.model_validate(payload)
    except ValidationError as exc:
        raise ValueError(f"Invalid quiz payload: {exc}") from exc
